language: node_js
cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
matrix:
  include:
  - os: osx
  - os: linux
    env: CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang
node_js:
  - "6"
  - "8"
  - "10"
script: "npm run-script test-travis"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
